#!/bin/bash

# Takes one parameter, which is the version of the distribution to create.

if [[ -z "$1" ]]; then
  echo "Usage: $0 version, where version is a number."
  exit 1
fi

version=$1

# Build the distribution directory and populate it with all of the source
# files.
basedir=cheloniidae-$version
mkdir $basedir
mkdir $basedir/cheloniidae

# Compile the documentation separately, since it makes a mess out of its working
# directory.
pushd doc
latex cheloniidae.tex && latex cheloniidae.tex && pdflatex cheloniidae.tex
popd

# Compile the literate code. This generates both a PDF and the source tree.
./cheloniidae compile
cp $(./cheloniidae pdf-output-file) doc/cheloniidae-literate.pdf

cp -r src/cheloniidae/* $basedir/cheloniidae/
cp examples/*.java $basedir/
cp doc/{cheloniidae.tex,cheloniidae.pdf,cheloniidae-literate.pdf} $basedir/
cp cheloniidae $basedir/cheloniidae-code-generator
cp doc/{CHANGELOG,README} $basedir/

# Now compile all of the Java files and examples.
cd $basedir
javac *.java cheloniidae/*.java cheloniidae/*/*.java

# Package the whole thing up into a zip file and delete the temporary
# directory.
cd ..
zip -r9 $basedir.zip $basedir
rm -rf $basedir
